stages:
  - build
  - deploy

default:
  image: quay.io/centos/centos:centos8

llvm:
  stage: build
  timeout: 6h

  tags:
    - ppc64le
    - docker
    - local

  only:
    - web
    - tags

  before_script:
    - dnf -y install epel-release
    - dnf -y install dnf-plugins-core
    - dnf config-manager --set-enabled powertools
    - dnf install -y ccache cmake clang llvm lld git make python2 ninja-build patch wget zstd

  script:
    - make

  artifacts:
    paths:
      - target/*-ppc64le.tar*

  cache:
    key: llvm-build-cache
    paths:
      - .ccache

github-release:
  stage: deploy
  timeout: 6h

  dependencies:
    - llvm

  tags:
    - ppc64le
    - docker
    - local

  only:
    - tags

  before_script:
    - dnf install -y make perl-Data-Dumper
    - dnf install -y perl-Net-GitHub-1.01-4.el8.noarch.rpm

  script:
    - make github-upload-release

