stages:
  - build
  - upload
  - release

default:
  image: quay.io/centos/centos:centos8

variables:
  VERSION: "0.0.0" # set semver to please the API
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/llvm-builds/${VERSION}"

build:
  stage: build
  timeout: 6h

  tags:
    - ppc64le
    - docker

  only:
    - web
    - tags

  before_script:
    - dnf -y install epel-release
    - dnf -y install dnf-plugins-core
    - dnf config-manager --set-enabled powertools
    - dnf install -y ccache cmake clang llvm lld git make python2 ninja-build patch wget zstd

  script:
    - make

  artifacts:
    paths:
      - target/*-ppc64le.tar*

  cache:
    key: llvm-build-cache
    paths:
      - .ccache

upload:
  stage: upload

  only:
    - tags

  tags:
    - ppc64le
    - docker

  script:
    - chmod +x ./upload.sh
    - ./upload.sh

release:
  stage: release

  tags:
    - ppc64le
    - docker

  only:
    - tags

  script:
    - chmod +x ./release.sh
    - ./release.sh
