stages:
  - build
  - deploy

default:
  image: fedora:latest

llvm:
  stage: build
  timeout: 6h

  tags:
    - ppc64le
    - docker
    - local

  only:
    - web
    - tags

  script:
    - dnf install -y ccache cmake gcc gcc-g++ git make ninja-build patch wget zstd
    - make

  artifacts:
    paths:
      - target/*-ppc64le.tar*

  cache:
    key: llvm-build-cache
    paths:
      - .ccache

github-release:
  stage: deploy
  timeout: 6h

  dependencies:
    - llvm

  tags:
    - ppc64le
    - docker
    - local

  only:
    - web
    - tags

  script:
    - dnf install -y make perl-Data-Dumper perl-Net-GitHub
    - make github-upload-release

